{{- if .Values.observability.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service-template.fullname" . }}
  labels: {{- include "service-template.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "service-template.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.observability.serviceMonitor.path }}
      interval: {{ .Values.observability.serviceMonitor.interval }}
{{- end }}
